### ISSUE TITLE
Passing  { report: 'json'} and other options to compileToString

### ISSUE THREAD

**Issue by kachkaev** [jfairbank/run-elm#10]
Hi @jfairbank!

I'm keen to implement a new feature, but am opening an issue instead of a PR because I'm not sure how to best approach it 😃 

My goal is to get errors from `run-elm` as JSON in order to display them to the user in a shiny interface with bells and whistles. This requires passing `--report=json` to the Elm compiler, which I can do by tweaking this line:

https://github.com/jfairbank/run-elm/blob/fca867a0666a92d3732d8b54d75993236651d8c5/src/index.js#L124
↓

```js
    const contents = await compileToString([mainModuleFilename], { yes: true, report: 'json' });
```

This suggests that we can just add a new option to `run-elm` called `--report` and simply pass its value down to `compileToString`. However, after a few experiments I can't say that this is enough. Here is what my brain is stuck with:

* Let's assume I want to run this Elm module with a hypothetical `--report` option:
  ```elm
  module Main exposing (..)

  hello: world
  I am a broken Elm module
  ```

  ```bash
   run-elm Main.elm --report=json
  ```
  Here's stderr after the first run (on a cold project):
  ```
  Error: Compilation failed
  Starting downloads...

  ● elm-lang/html 2.0.0
  ● elm-lang/virtual-dom 2.0.4
  ● elm-lang/core 5.1.1

  Packages configured successfully!
  [{"tag":"SYNTAX PROBLEM","overview":"It looks like the keyword `module` is being used as a variable.","subregion":null,"details":"Rename it to something else.","region":{"start":{"line":4,"column":25},"end":{"line":4,"column":25}},"type":"error","file":"././Main.elm"}]
  ```

  And here is what Elm returns after the second run (when `elm-stuff` already exists):

  ```
  Error: Compilation failed
  [{"tag":"SYNTAX PROBLEM","overview":"It looks like the keyword `module` is being used as a variable.","subregion":null,"details":"Rename it to something else.","region":{"start":{"line":4,"column":25},"end":{"line":4,"column":25}},"type":"error","file":"././Main.elm"}]
  ``` 
  As you can see, `stdout` is not stable and is therefore not straightforward to parse or test. And if we manage to trim `Error: Compilation failed` etc., should we also take responsibility and report other possible issues as JSON such as a syntax error in `package-elm.json`? I'm not sure what's best to do.

* What if we want to pass more options down to `compileToString` in addition to `--report=json`? Isn't there a more general and thus better way to solve what I'm trying to achieve?

---

I just submitted https://github.com/jfairbank/run-elm/pull/9 as a first step towards what I'd like to add to `run-elm` and I'm keen to hear your feedback!

**Comment by kachkaev** [comment]
Speaking of picking a JSON from the raw output, perhaps, just grabbing the last row in `stderr` is enough? Just like I did in https://github.com/jfairbank/run-elm/issues/11#issuecomment-370897728 🤔 

In this case, we can add  a `--report` option which accepts any string and simply pass it to `elm-make`. @jfairbank would you pre-approve a PR that does this?

**Comment by kachkaev** [comment]
ping @jfairbank 🙏

**Comment by jfairbank** [comment]
This isn't really a use case that I had envisioned, but it still seems like a reasonable thing to add. It's tricky to parse like you mention, though. It's possible you could also get warnings as well as errors.

Given this module:

```elm
module Foo exposing (..)

import Html


main =
    Html.text
```

You would end up with this:

```
[{"tag":"missing type annotation","overview":"Top-level value `main` does not have a type annotation.","details":"I inferred the type annotation so you can copy it into your code:\n\nmain : String -> Html.Html msg","region":{"start":{"line":6,"column":1},"end":{"line":6,"column":5}},"type":"warning","file":"Foo.elm"}]
[{"tag":"BAD MAIN TYPE","overview":"The `main` value has an unsupported type.","subregion":null,"details":"I need Html, Svg, or a Program so I have something to render on screen, but you\ngave me:\n\n    String -> Html.Html msg","region":{"start":{"line":6,"column":1},"end":{"line":6,"column":5}},"type":"error","file":"Foo.elm"}]
```

Maybe you could split on newlines and parse backwards with `JSON.parse` until it throws and then stop? Then, you could capture all possible warnings/errors.

As far as making `--report` general purpose or not, I'm fine keeping it specific for now because I honestly don't know what other use cases we might want in the future.

**Comment by kachkaev** [comment]
So if I just add a new option and pass it down to a sub-process, would that be OK for you? With tests, of course 🚦 

Output parsing is what I'll be doing outside `run-elm`, line by line in reverse order as you suggest.

**Comment by jfairbank** [comment]
Yes, sounds good to me.
