### ISSUE TITLE
Configure AppVeyor

### ISSUE THREAD

**Issue by kachkaev** [jfairbank/run-elm#16]
It'd be great to see AppVeyor configured for this repo given that appveyor.yml already exists. I've been using this CI in my fork (https://ci.appveyor.com/project/kachkaev/run-elm) and it helpd find a couple of pretty nasty bugs on Windows!

**Comment by kachkaev** [comment]
ping @jfairbank 😉

**Comment by jfairbank** [comment]
@kachkaev It's configured, and I added a badge to the README. Let me know if something looks wrong (not used AppVeyor before). Thanks.

**Comment by kachkaev** [comment]
Looks good to me! Thank you for looking into this and congrats about Elm 0.19! 🎉
