### ISSUE TITLE
elm-package.json is ignored when the elm file to run is in a subdirectory

### ISSUE THREAD

**Issue by kachkaev** [jfairbank/run-elm#3]
Hi @jfairbank and thanks for this nice tool! Here's a small issue you might want to have a look at in future.

I've got a few subfolders in my elm projects and I'd like to execute `run-elm /path/to/project/path/to/subfolder/Module.elm`. Despite that there exist `elm-package.json` and `elm-stuff` in `/path/to/project`, these assets are being created in `path/to/subfolder`. When the original `elm-package.json` contains links to non-core third-party modules, `run-elm` fails because a new `elm-package.json` does not include much.

It'd be great if `run-elm` searched for the closest `elm-package.json` before deciding to initialize a new project!

**Comment by jfairbank** [comment]
Thanks for the suggestion and your kind words @kachkaev! I can't address this soon, but you're welcome to open a PR if you want.
