### ISSUE TITLE
Make the name of the output variable customisable

### ISSUE THREAD

**Issue by kachkaev** [jfairbank/run-elm#4]
To see some data in stdout with `run-elm`, it is currently necessary to specify `output : String` within the module. Although this is not a problem for the files written by hand, a naming collision may occur if `output : String` is appended programmatically to some user-written code. It'd be great if it was possible to define the name of the output variable like this:

```bash
run-elm Module.elm --output-var=output42
```

**Comment by jfairbank** [comment]
@kachkaev I'm not sure how often the name clash would realistically happen, but it could still be a nice customization. You're welcome to open a PR for this if you want.

**Comment by kachkaev** [comment]
Closed by #5
